2024-01-18 13:06:47,405-INFO-|Energy consumed for RAM : 0.000049 kWh. RAM Power : 5.868003845214844 W|/n
2024-01-18 13:06:47,406-INFO-|Energy consumed for all CPUs : 0.000117 kWh. Total CPU Power : 14.0 W|/n
2024-01-18 13:06:47,406-INFO-|0.000166 kWh of electricity used since the beginning.|/n
2024-01-18 13:07:17,421-INFO-|Energy consumed for RAM : 0.000098 kWh. RAM Power : 5.868003845214844 W|/n
2024-01-18 13:07:17,421-INFO-|Energy consumed for all CPUs : 0.000233 kWh. Total CPU Power : 14.0 W|/n
2024-01-18 13:07:17,421-INFO-|0.000331 kWh of electricity used since the beginning.|/n
2024-01-18 13:07:32,193-INFO-|Energy consumed for RAM : 0.000122 kWh. RAM Power : 5.868003845214844 W|/n
2024-01-18 13:07:32,193-INFO-|Energy consumed for all CPUs : 0.000291 kWh. Total CPU Power : 14.0 W|/n
2024-01-18 13:07:32,193-INFO-|0.000413 kWh of electricity used since the beginning.|/n
2024-01-18 13:07:32,220-ERROR-|type NoneType doesn't define __round__ method|/n
Traceback (most recent call last):
  File "C:\Users\sabri\OneDrive\Desktop\projectCodecarbon - Github\ProjectCodecarbon-Javascript-Program\public\logger.py", line 48, in <module>
    model = train_model()
            ^^^^^^^^^^^^^
  File "C:\Users\sabri\OneDrive\Desktop\projectCodecarbon - Github\ProjectCodecarbon-Javascript-Program\public\logger.py", line 42, in train_model
    time.sleep(delay)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sabri\anaconda3\envs\projectCodecarbon\Lib\site-packages\codecarbon\core\api_client.py", line 123, in _create_run
    longitude=round(self.conf.get("longitude"), 1),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type NoneType doesn't define __round__ method
2024-01-18 13:07:32,222-ERROR-|ApiClient.add_emission still no run_id, aborting for this time !|/n
